aplicacion.nombre=core-person-client-account-movement
server.port=${port:1602}
path.webservice=person-client

resource-config.datasource.jdbc-url=jdbc:postgresql://localhost:5432/banco_db
resource-config.datasource.username=postgres
resource-config.datasource.password=12345
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.maximum-pool-size=200
spring.datasource.hikari.minimum-idle=20
spring.datasource.hikari.max-lifetime=600000
spring.datasource.platform=postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.initialization-mode=always
resource-config.datasource.driver=org.postgresql.Driver
javax.persistence.lock.timeout=600000

grpc.client.timeout.idle=5
grpc.client.timeout.deadline-after=60
grpc.client-server.map={}
grpc.server.port=9090
